name: Terraform CI

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform plan and apply
    runs-on: ubuntu-20.04
    container: hashicorp/terraform:1.0.1

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform plan -out infra.tfplan

      - name: Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply infra.tfplan
