name: Terraform Deploy
on:
  workflow_dispatch:
    inputs:
      terraform_version:
        description: Terraform Version
        default: 0.15.5
        required: false
    branches:
      - main

env:
  GITHUB_SHA: {% raw %}${{ github.sha }}{% endraw %}
  AWS_REGION: us-east-1

jobs:
  deploy-infrastructure:
    name: Plan and Apply
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Terraform Plan
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: {% raw %}${{ github.event.inputs.terraform_version }}{% endraw %}
        tf_actions_subcommand: plan -out infra.tfplan
        tf_actions_working_dir: .
      env:
        GITHUB_TOKEN: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
        AWS_ACCESS_KEY_ID: {% raw %}${{ secrets.AWS_ACCESS_KEY_ID }}{% endraw %}
        AWS_SECRET_ACCESS_KEY: {% raw %}${{ secrets.AWS_SECRET_ACCESS_KEY }}{% endraw %}
        AWS_DEFAULT_REGION: $AWS_REGION

    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: {% raw %}${{ github.event.inputs.terraform_version }}{% endraw %}
        tf_actions_subcommand: apply infra.tfplan
        tf_actions_working_dir: .
      env:
        GITHUB_TOKEN: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
        AWS_ACCESS_KEY_ID: {% raw %}${{ secrets.AWS_ACCESS_KEY_ID }}{% endraw %}
        AWS_SECRET_ACCESS_KEY: {% raw %}${{ secrets.AWS_SECRET_ACCESS_KEY }}{% endraw %}
        AWS_DEFAULT_REGION: $AWS_REGION
